### ISSUE TITLE
[US 3] Visualize Friend's post

### ISSUE THREAD

**Issue by VictorML11** [UB-ES-19/A3-LikeMe#27]
**Description:** 
> As a user I want to see my friends post in the main page after log in.

**Time:** 
> 2h

**Comment by VictorML11** [comment]
1. From **Backend** we need to send the data when the user joins to the main page after log in
2. From **Frontend** we need to show the data {Posts}

**Comment by VictorML11** [comment]
Backend part **done**  any updates on this from Frontend?

**Comment by macsimdl** [comment]
I'm working on frontend part of the profile page, tomorrow will be done. After doing it I'll work on other profiles frontend

**Comment by lydia-cs** [comment]
Visualization done. Waiting for your pull request to be accepted, so I can merge it to verify there are no problems.
